### ISSUE TITLE
the python files are not saved in ".py" extension

### ISSUE THREAD

**Issue by ombharamadev** [KHUshi-240/KHUshi-240-Khushi#1]
![image](https://github.com/KHUshi-240/KHUshi-240-Khushi/assets/150242178/3b969969-64b2-4c28-93fd-5a17dcb69024)
the python files are not saved in ".py" extension 
update the all file with ".py"

**Comment by KHUshi-240** [comment]
Updated

**Comment by KHUshi-240** [comment]
Updated

**Comment by ombharamadev** [comment]
ok
